

import React from 'react'

export const metadata = {
  title: "About Us | Ecommerce Website",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <h1>About Us</h1>
    </div>
  )
}
