"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

import { store } from './redux-toolkit/store/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Ecommerce Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
          <Header/>
          {children}
      </Provider>
      </body>
    </html>
  );
}
