import Products from "@/app/Components/Products";

export const metadata = {
    title: "Categories | Ecommerce Website",
    description: "Generated by create next app",
};

export default function page() {

  return (
    <div>
      <Products/>
    </div>
  )
}
